name: Bot Twitter API Profesional

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Lo bajamos a cada 30 min para ser más discretos con la API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests tweepy

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        run: python bot.py

      - name: Save memory
        run: |
          git config --global user.name "BotInversiones"
          git config --global user.email "bot@inversiones.com"
          git pull --rebase origin main
          # Esta línea evita el error si no hay archivos .txt aún
          touch last_id_inicio.txt 
          git add last_id_*.txt
          git commit -m "Actualizar memoria de API" || exit 0
          git push origin main
