name: Bot Fotografo Inversiones

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 # <-- CORREGIDO AQUÃ
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps chromium # Agregamos --with-deps para evitar errores de sistema

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          X_USER: ${{ secrets.X_USER }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
        run: python bot.py

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Save memory
        run: |
          git config --global user.name "BotInversiones"
          git config --global user.email "bot@inversiones.com"
          git add *.txt
          git commit -m "Actualizar memoria de tweets" || exit 0
          git push
